version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres_blog_app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_blog_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./nest-blog-app
    container_name: nest_blog_app
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres_blog_app
    depends_on:
      - postgres

  frontend:
    build: ./next-blog-app
    container_name: next_blog_app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: